import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 4 }
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 16
